### ISSUE TITLE
Problem with GLIBCXX

### ISSUE THREAD

**Issue by d-krupke** [CG-SHOP/pyutils23#12]
Conda and Ubuntu LTS:
```
ImportError while importing test module '/misc/ibr/home/krupke/pyutils23/tests/test_iterator.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/ibr/home/krupke/anaconda3/envs/cgshop/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_iterator.py:3: in <module>
    from cgshop2023_pyutils.zip import ZipSolutionIterator
/ibr/home/krupke/anaconda3/envs/cgshop/lib/python3.9/site-packages/cgshop2023_pyutils/__init__.py:23: in <module>
    from .verifier import verify
/ibr/home/krupke/anaconda3/envs/cgshop/lib/python3.9/site-packages/cgshop2023_pyutils/verifier/__init__.py:9: in <module>
    from ..core import (
/ibr/home/krupke/anaconda3/envs/cgshop/lib/python3.9/site-packages/cgshop2023_pyutils/core/__init__.py:6: in <module>
    from ._cgshop2023_core import (
E   ImportError: /misc/ibr/home/krupke/anaconda3/envs/cgshop/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /ibr/home/krupke/anaconda3/envs/cgshop/lib/python3.9/site-packages/cgshop2023_pyutils/core/_cgshop2023_core.cpython-39-x86_64-linux-gnu.so)
```

**Comment by phillip-keldenich** [comment]
This is because some of our systems have different libstdc++ versions, and apparently the system that you're running this on has an older version than the one on which the shared library was built.

**Comment by d-krupke** [comment]
`conda install -c conda-forge gxx` and reinstalling solved the problem for me.

**Comment by d-krupke** [comment]
> This is because some of our systems have different libstdc++ versions, and apparently the system that you're running this on has an older version than the one on which the shared library was built.
> 
> I think this is an artifact of installing newer compiler versions on some of the systems, but I'm not sure.
> 
> Unless I'm mistaken, a compiler/linker will probably require the version of the standard lib it links against as baseline, and the resulting binaries should work on systems with that version (or higher). If I am mistaken, then it might actually require the version to match exactly, but I don't think that's the case.
> 
> There are actually surprisingly recent changes to some of the symbols/symbol versions even in the GNU standard C library. I leared that when building pre-built linux binaries for some earlier contest; some stuff including compiler-generated calls to memcpy was triggering dyamic loading errors when run on systems with other GNU standard C libraries.

The library was completely compiled on that system. The problem is that conda ships its own glibc, but if the conda environment does not have a C++ compiler, it will use the system's compiler and link against the wrong version.

**Comment by d-krupke** [comment]
`conda install -c conda-forge cxx-compiler` for conda users may be more generic. Will update the documentation.

**Comment by d-krupke** [comment]
Added comment.
