### ISSUE TITLE
Couldn't install via pip

### ISSUE THREAD

**Issue by hieu-lee** [CG-SHOP/pyutils23#15]
I got these error messages when I try to install the package via pip, I'm using Ubuntu 20.04
```
ERROR: Could not find a version that satisfies the requirement csghop2023-pyutils (from versions: none)
ERROR: No matching distribution found for csghop2023-pyutils
```

**Comment by d-krupke** [comment]
Hey,
Can you tell me which version of python and pip you are using? You can get this information using `python --version` and `pip --version`.

**Comment by hieu-lee** [comment]
I'm having python 3.10.7 and pip 22.3.1

**Comment by d-krupke** [comment]
That is very odd because the package is listed [here](https://pypi.org/project/cgshop2023-pyutils/) correctly to be compatible with Python[>=3.7]. It some odd cases, pip links to the Python2 version and you have to use `pip3` instead.

You can alternatively also just download the repository and execute `pip install .` within the folder.

**Comment by hieu-lee** [comment]
I downloaded the repo and ran `pip install .` but I got these errors:

```
Building wheels for collected packages: cgshop2023-pyutils
  Building wheel for cgshop2023-pyutils (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for cgshop2023-pyutils (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [72 lines of output]
      Configuration:
      [settings]
      arch=x86_64
      arch_build=x86_64
      build_type=Release
      compiler=gcc
      compiler.libcxx=libstdc++
      compiler.version=9
      os=Linux
      os_build=Linux
      [options]
      [build_requires]
      [env]

      Version ranges solved
          Version range '==5.3' required by 'conanfile.txt' resolved to 'cgal/5.3.2' in local cache
          Version range '>=3.11' required by 'conanfile.txt' resolved to 'nlohmann_json/3.11.2' in local cache

      conanfile.txt: Installing package
      Requirements
          boost/1.75.0 from 'conancenter' - Cache
          bzip2/1.0.8 from 'conancenter' - Cache
          cgal/5.3.2 from 'conancenter' - Cache
          eigen/3.3.9 from 'conancenter' - Cache
          gmp/6.2.1 from 'conancenter' - Cache
          libbacktrace/cci.20210118 from 'conancenter' - Cache
          mpfr/4.1.0 from 'conancenter' - Cache
          nlohmann_json/3.11.2 from 'conancenter' - Cache
          zlib/1.2.13 from 'conancenter' - Cache
      Packages
          boost/1.75.0:adf48b8e4446dcb68f440fe42ff08878d5c7feed - Cache
          bzip2/1.0.8:da606cf731e334010b0bf6e85a2a6f891b9f36b0 - Cache
          cgal/5.3.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          eigen/3.3.9:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          gmp/6.2.1:7afb5e29f0f97ee06c193341f7883a4aefd39a8c - Cache
          libbacktrace/cci.20210118:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache
          mpfr/4.1.0:2a345fab1896a5e7007785742bbfa07f780e3aa2 - Cache
          nlohmann_json/3.11.2:5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9 - Cache
          zlib/1.2.13:6af9cc7cb931c5ad942174fd7838eb655717c709 - Cache

      Installing (downloading, building) binaries...
      bzip2/1.0.8: Already installed!
      eigen/3.3.9: Already installed!
      gmp/6.2.1: Already installed!
      libbacktrace/cci.20210118: Already installed!
      nlohmann_json/3.11.2: Already installed!
      zlib/1.2.13: Already installed!
      boost/1.75.0: Already installed!
      mpfr/4.1.0: Already installed!
      cgal/5.3.2: Already installed!
      conanfile.txt: Generator cmake_find_package created FindCGAL.cmake
      conanfile.txt: Generator cmake_find_package created Findnlohmann_json.cmake
      conanfile.txt: Generator cmake_find_package created FindBoost.cmake
      conanfile.txt: Generator cmake_find_package created FindEigen3.cmake
      conanfile.txt: Generator cmake_find_package created Findmpfr.cmake
      conanfile.txt: Generator cmake_find_package created FindZLIB.cmake
      conanfile.txt: Generator cmake_find_package created FindBZip2.cmake
      conanfile.txt: Generator cmake_find_package created Findlibbacktrace.cmake
      conanfile.txt: Generator cmake_find_package created Findgmp.cmake
      conanfile.txt: Generator txt created conanbuildinfo.txt
      conanfile.txt: Aggregating env generators
      conanfile.txt: Generated conaninfo.txt
      conanfile.txt: Generated graphinfo
      Traceback (most recent call last):
        File "/tmp/pip-build-env-fgc45re9/overlay/local/lib/python3.10/dist-packages/skbuild/setuptools_wrap.py", line 612, in setup
          cmkr = cmaker.CMaker(cmake_executable)
        File "/tmp/pip-build-env-fgc45re9/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 148, in __init__
          self.cmake_version = get_cmake_version(self.cmake_executable)
        File "/tmp/pip-build-env-fgc45re9/overlay/local/lib/python3.10/dist-packages/skbuild/cmaker.py", line 103, in get_cmake_version
          raise SKBuildError(

      Problem with the CMake installation, aborting build. CMake executable is cmake
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cgshop2023-pyutils
Failed to build cgshop2023-pyutils
ERROR: Could not build wheels for cgshop2023-pyutils, which is required to install pyproject.toml-based projects
```

**Comment by phillip-keldenich** [comment]
Interesting - what kind of problem could it have with your CMake installation?
What happens if you run the cmake command?

**Comment by d-krupke** [comment]
Ohh. Maybe our cmake version requirement is to high for an LTS system.
You could try to just edit CMakeLists.txt and lower the version e.g. to `cmake_minimum_required(VERSION 3.17)`, which I believe should still work.

**Comment by d-krupke** [comment]
However, in this case I would actually believe scikit-build would have provided a better error message... but you could check the version of your cmake. If it is below 3.21 it may be too old for our script and you need to make the change of above.

**Comment by phillip-keldenich** [comment]
Could we also try to avoid this situation by requiring a reasonably recent CMake version in the conan dependencies?
Well, I guess it may be difficult to convince skbuild of using that version if it invokes CMake itself...

**Comment by d-krupke** [comment]
Yes. We should do that. 3.21 has only been release 1.5years ago which is to new for some systems.

**Comment by d-krupke** [comment]
Ohh. We could also just state the dependency cmake[>=3.21] as it is available from PyPI. Don't know if this may interferes with the system's cmake. Reducing the required version should be easier.

**Comment by phillip-keldenich** [comment]
Hm, I guess this will install another cmake that will be on the path inside the environment where the package is installed.
This will probably sidestep the issue of making scikit-build find that version of CMake that we would have with using conan to install CMake, so its a big upgrade on that idea.

I don't know what version of CMake is safe to drop back to. < 3.16 is very probably broken for our purposes because of how FindPython works with python virtual environments there (it doesn't really). 3.17 (as you suggested) may work.

**Comment by d-krupke** [comment]
I lowered the required CMake version and defined the necessary version in the toml. @hieu-lee  maybe you could test this so I can close this issue?

**Comment by hieu-lee** [comment]
I worked when I do `pip install .` but it still doesn't work when I try `pip install csghop2023-pyutils`

**Comment by d-krupke** [comment]
Ok. I just checked: Ubuntu 20.04 LTS comes with cmake 3.16. So 3.17 is still too new. The build requirement only seems to work when installing it directly, not via PyPI (otherwise it should have failed too using the local installation). I don't know if 3.16 would still be ok for building.

**Comment by d-krupke** [comment]
Maybe we have to specify the required cmake version by `cmake_minimum_required_version="3.17",` in the `setup.py` and can not only specify it within the `CMakeList.txt`.

**Comment by d-krupke** [comment]
The latest version should fix this problem. @hieu-lee if you find the time, it would be nice of you to check it. Otherwise, I will just close this issue in a few days.
