### ISSUE TITLE
Issues with user rights when installing

### ISSUE THREAD

**Issue by rolfvdhulst** [CG-SHOP/pyutils23#4]
I had some issues when installing: 

Changing the step:
```
python3 setup.py install
```

to:

```
python3 setup.py install  --user
``` 

Fixed it for me.

**Comment by d-krupke** [comment]
Thanks for the hint. That problem can occur for some environments. I did not make it default, because it seems that using '--user' can do some unexpected things in virtual environments. However, I added this as a fallback mode.
